import Navbar from './components/navbar/Navbar'
import Modal from './components/modals/Modal'
import './globals.css'
import { Inter } from 'next/font/google'
import RegisterModal from './components/modals/RegisterModal'
import ToasterProvider from './components/providers/ToasterProvider'
import LoginModal from './components/modals/LoginModal'

import getCurrentUser from './actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider/>
        <LoginModal />
        <RegisterModal/>
        <Navbar currentUser={currentUser}/>
        
        {children}
        </body>
    </html>
  )
}
